//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course_project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InventoryDBContext : DbContext
    {
        public InventoryDBContext()
            : base("name=InventoryDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<InventoryCard> InventoryCard { get; set; }
        public virtual DbSet<MovementNote> MovementNote { get; set; }
        public virtual DbSet<PurchaseCompany> PurchaseCompany { get; set; }
        public virtual DbSet<PurchaseMemo> PurchaseMemo { get; set; }
        public virtual DbSet<RepairCompany> RepairCompany { get; set; }
        public virtual DbSet<RepairNote> RepairNote { get; set; }
        public virtual DbSet<Responsible> Responsible { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WriteOffMemo> WriteOffMemo { get; set; }
        public virtual DbSet<group_inventory_by_resp> group_inventory_by_resp { get; set; }
        public virtual DbSet<inventory_by_resp_by_address> inventory_by_resp_by_address { get; set; }
        public virtual DbSet<inventory_without_guarantee_by_resp> inventory_without_guarantee_by_resp { get; set; }
        public virtual DbSet<inventory_without_repairs> inventory_without_repairs { get; set; }
        public virtual DbSet<purchased_inventory_by_years> purchased_inventory_by_years { get; set; }
        public virtual DbSet<responsibles_who_needed_repair> responsibles_who_needed_repair { get; set; }
        public virtual DbSet<summary_for_inventory_repairs> summary_for_inventory_repairs { get; set; }
    
        public virtual ObjectResult<CheckGuarantee_Result> CheckGuarantee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CheckGuarantee_Result>("CheckGuarantee");
        }
    
        public virtual ObjectResult<FindExpired_Result> FindExpired()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FindExpired_Result>("FindExpired");
        }
    
        public virtual ObjectResult<ShowWrittenOffInventory_Result> ShowWrittenOffInventory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowWrittenOffInventory_Result>("ShowWrittenOffInventory");
        }
    }
}
