//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory()
        {
            this.MovementNote = new HashSet<MovementNote>();
            this.PurchaseMemo = new HashSet<PurchaseMemo>();
            this.WriteOffMemo = new HashSet<WriteOffMemo>();
            this.RepairNote = new HashSet<RepairNote>();
        }
    
        public int InventoryID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<System.DateTime> WithdrawalDate { get; set; }
        public Nullable<System.DateTime> GuaranteeDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> InventoryCardID { get; set; }
        public Nullable<int> ResponsibleID { get; set; }
        public string SerialNumber { get; set; }
        public string InventoryName { get; set; }
        public string Condition { get; set; }
        public string SpecialSoftware { get; set; }
        public Nullable<long> InventoryNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovementNote> MovementNote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseMemo> PurchaseMemo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WriteOffMemo> WriteOffMemo { get; set; }
        public virtual InventoryCard InventoryCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepairNote> RepairNote { get; set; }
        public virtual Responsible Responsible { get; set; }
    }
}
