//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementNote
    {
        public int MovementNoteID { get; set; }
        public System.DateTime MovementDate { get; set; }
        public int PreviousResponsibleID { get; set; }
        public int CurrentResponsibleID { get; set; }
        public int InventoryID { get; set; }
        public string Notes { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Responsible Responsible { get; set; }
        public virtual Responsible Responsible1 { get; set; }
    }
}
