//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseMemo
    {
        public int PurchaseMemoID { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime DateOfPurchase { get; set; }
        public int PurchasableInventoryID { get; set; }
        public int PurchaseCompanyID { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual PurchaseCompany PurchaseCompany { get; set; }
    }
}
