//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchased_inventory_by_years
    {
        public Nullable<int> Год { get; set; }
        public string Название_оборудования { get; set; }
    }
}
