//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WriteOffMemo
    {
        public int WriteOffMemoID { get; set; }
        public int InventoryID { get; set; }
        public System.DateTime WriteOffDate { get; set; }
    
        public virtual Inventory Inventory { get; set; }
    }
}
